### ISSUE TITLE
Data Analysis Onboarding

### ISSUE THREAD

**Issue by jessicajcho** [cornellh4i/H4I_EEW_Industry_Reports#1]
### Onboarding Tasks

1. Clone the H4I_EEW_Industry_Reports repository on GitHub 
2. Run git branch -b “<your_name>-onboarding”
This creates your own branch called “name-onboarding”  
3. Read: https://www.census.gov/naics/?48967
      - This is the spreadsheet with the NAICS names/data and associated codes:
         https://docs.google.com/spreadsheets/d/1u8EioUt7QD8fxz73N6JLHjgMzCuCbCvJ/edit#gid=1754842729
4. There are different ways to edit/run your code. We recommend that you copy-paste the entire repo folder into a Google Drive folder on your Google account– and then you can edit & run your code in Google CoLab. Then, in general, when updating the Git repository, you can download the CoLab code into your file directory / update using VSCode or local terminal. 
5. Go to NAICS_SELECTOR.ipynb and do the following:
       - Run all the cells in the CoLab notebook. 
       - In the second cell, make sure to select a program and input a valid NAICS code (see the linked google sheets above). 
          Otherwise, the next cell will throw an error.
       - As the **task**, upload a screenshot of the map 
6. Take a look at the backend_scripts folder 
       - Look through the python scripts in this folder and get a basic gist of the functionality
7. ***Optional*** Python Onboarding (can skip if you are confident in Python already) 
       - https://www.programiz.com/python-programming 
       - [Python 101](https://www.youtube.com/watch?v=mMv6OSuitWw&pp=ygUNcHl0aG9uIGJhc2ljcw%3D%3D)
       - Pandas:
       - https://pandas.pydata.org/docs/user_guide/10min.html
       - https://pandas.pydata.org/docs/
       - https://www.datacamp.com/tutorial/pandas

**Comment by ashukla9** [comment]
<img width="302" alt="Screenshot 2023-09-23 131622" src="https://github.com/cornellh4i/H4I_EEW_Industry_Reports/assets/68243595/8d2ceb87-ff02-4ee0-914e-e6c161a6146f">

**Comment by juliapapp24** [comment]
<img width="885" alt="Screenshot 2023-09-23 at 1 18 00 PM" src="https://github.com/cornellh4i/H4I_EEW_Industry_Reports/assets/91167835/3bad6260-9496-498c-a9e6-77b9b7156d35">

**Comment by sesebear** [comment]
<img width="1390" alt="Screenshot 2023-09-23 at 5 27 08 PM" src="https://github.com/cornellh4i/H4I_EEW_Industry_Reports/assets/145622203/ebc59829-e9ca-47d8-81b9-a5f015aa809e">

**Comment by ezhong0211** [comment]
<img width="786" alt="image" src="https://github.com/cornellh4i/H4I_EEW_Industry_Reports/assets/112904303/ec04476f-1ef0-4dc9-8d58-5bf3d2674a55">
