### ISSUE TITLE
Web Dev Onboarding

### ISSUE THREAD

**Issue by JJBai2003** [cornellh4i/H4I_EEW_Industry_Reports#2]
### Onboarding Tasks

1. Clone the H4I_EEW_Industry_Reports repository on GitHub 
2. Run git branch -b “<your_name>-onboarding”
This creates your own branch called “name-onboarding”  
3. Read: https://www.census.gov/naics/?48967
      - This is the spreadsheet with the NAICS names/data and associated codes:
         https://docs.google.com/spreadsheets/d/1u8EioUt7QD8fxz73N6JLHjgMzCuCbCvJ/edit#gid=1754842729
4. There are different ways to edit/run your code. We recommend that you copy-paste the entire repo folder into a Google Drive folder on your Google account– and then you can edit & run your code in Google CoLab. Then, in general, when updating the Git repository, you can download the CoLab code into your file directory / update using VSCode or local terminal. 
5. Go to NAICS_SELECTOR.ipynb and do the following:
       - Run all the cells in the CoLab notebook. 
       - In the second cell, make sure to select a program and input a valid NAICS code (see the linked google sheets above). 
          Otherwise, the next cell will throw an error.
- [ ] As the **task**, upload a screenshot of the map 

6. Take a look at the backend_scripts folder 
       - Look through the python scripts in this folder and get a basic gist of the functionality
7. Streamlit Onboarding 
- [ ] Install Streamlit using [these instructions](https://docs.streamlit.io/library/get-started/installation) 
- [ ] Skim through Streamlit [main concepts](https://docs.streamlit.io/library/get-started/main-concepts)
- [ ] Go through the steps of [Create an App on Streamlit](https://docs.streamlit.io/library/get-started/create-an-app)- Go through “Create your first app” and “Fetch some data”

**Comment by ashukla9** [comment]
<img width="302" alt="Screenshot 2023-09-23 131622" src="https://github.com/cornellh4i/H4I_EEW_Industry_Reports/assets/68243595/075e08a0-6089-44ab-bd9b-229d5f40bb50">
